- hosts: extracter
  vars:
    - roswell_version: master
    - parser_version: no-ignore-errors
    - extracter_deploy_path: /srv/www/quickdocs-extracter
    - updater_deploy_path: /srv/www/quickdocs-updater
  pre_tasks:
    - user: name=git home=/srv/git
      sudo: yes
    - user: name=www home=/srv/www
      sudo: yes
    - shell: chmod 777 /srv/www
      sudo: yes
  roles:
    - common
    - roswell
    - docker
    - { role: quickdocs-extracter, deploy_path: "{{ extracter_deploy_path }}" }
    - { role: quickdocs-updater, deploy_path: "{{ updater_deploy_path }}" }
  tasks:
    - name: docker build
      shell: scripts/build-docker-image
      chdir: {{ extracter_deploy_path }}