- hosts: extracter
  vars:
    - roswell_version: master
    - parser_version: no-ignore-errors
    - extracter_deploy_path: /srv/www/quickdocs-extracter
    - updater_deploy_path: /srv/www/quickdocs-updater
    - database_deploy_path: /srv/www/quickdocs-database
  pre_tasks:
    - user: name=git home=/srv/git
      sudo: yes
    - user: name=www home=/srv/www
      sudo: yes
    - shell: chmod 777 /srv/www
      sudo: yes
  roles:
    - common
    - roswell
    - docker
    - { role: quickdocs-extracter, deploy_path: "{{ extracter_deploy_path }}" }
    - { role: quickdocs-updater, deploy_path: "{{ updater_deploy_path }}", database_deploy_path: "{{ database_deploy_path }}" }
  tasks:
    - name: docker build
      shell: scripts/build-docker-image
      chdir: {{ extracter_deploy_path }}
    - name: create db
      shell: mysql -uroot -e "CREATE DATABASE 'quickdocs' DEFAULT CHARACTER SET utf8"
    - name: create tables
      shell: mysql -uroot quickdocs < db/schema.sql
      chdir: {{ database_deploy_path }}